kind: pipeline
type: docker
name: default

steps:
- name: deploy nuGet package
  image: microsoft/dotnet:2.0-sdk
  pull: if-not-exists
  commands:
  - dotnet restore
  - dotnet build
  - dotnet pack
  - dotnet nuget push

trigger:
  branch:
  - CP-1965_ci-deployment
